 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_jajeem_licensing_LicenseManager */

#ifndef _Included_com_jajeem_licensing_LicenseManager
#define _Included_com_jajeem_licensing_LicenseManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jajeem_licensing_LicenseManager
 * Method:    Authenticate
 * Signature: (Z)Z
 */
JNIEXPORT jint JNICALL Java_com_jajeem_licensing_LicenseManager_Authenticate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
