package com.jajeem.util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class initDatabase {

	public static void initialize() {
		Connection con;
		try {
			con = BaseDAO.getConnection();
			String query = "";
			query += "CREATE TABLE QuizQuestion (Quizid int NOT NULL, id int NOT NULL, title varchar(5000), type tinyint NOT NULL, point int, imagepath varchar(1000), url varchar(555), answer1 varchar(555), answer2 varchar(555), answer3 varchar(555), answer4 varchar(555), answer5 varchar(555), Instructorid2 int NOT NULL, PRIMARY KEY (Quizid, id));"+
					 "CREATE TABLE QuizRun (Quizid int NOT NULL, Instructorid int NOT NULL, start int, end int, id int NOT NULL, sessionId int NOT NULL, Studentid int NOT NULL, PRIMARY KEY (id, sessionId));"+
					 "CREATE TABLE Quiz (id int GENERATED BY DEFAULT AS IDENTITY, instructorid int NOT NULL, type tinyint, category varchar(255), description varchar(1000), pointing int, points int, time int, shuffle tinyint, title varchar(255), PRIMARY KEY (id));"+
					 "CREATE TABLE Reponse (QuizRunid int, QuizRunsessionId int, answer varchar(555), Studentid int NOT NULL, id int GENERATED BY DEFAULT AS IDENTITY, bool1 varchar(5), bool2 varchar(5), bool3 varchar(5), bool4 varchar(5), bool5 varchar(5), PRIMARY KEY (id));"+
					 "ALTER TABLE QuizQuestion ADD CONSTRAINT FKQuizQuesti740493 FOREIGN KEY (Quizid) REFERENCES Quiz (id);"+
					 "ALTER TABLE QuizRun ADD CONSTRAINT FKQuizRun478787 FOREIGN KEY (Quizid) REFERENCES Quiz (id);"+
					 "ALTER TABLE Reponse ADD CONSTRAINT FKReponse175471 FOREIGN KEY (QuizRunid, QuizRunsessionId) REFERENCES QuizRun (id, sessionId);";

			Statement statement = con.createStatement();
			statement.executeUpdate(query);
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
		
	}

}
