package com.jajeem.util;

import java.util.UUID;

public class Query {

	public static String summaryOfStudents(UUID quizRunId) {
		return "SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE, STUDENTID, STUDENTNAME, COUNT(ANSWERVALID) QUESTIONCOUNT, SUM(AV) VALIDANSWERS, SUM(AV)*100/COUNT(ANSWERVALID) PERCENTS, SUM(AV)*QUIZPOINTS/COUNT(ANSWERVALID)POINTS "
				+ "FROM ( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND', QRN.START/1000, DATE '1970-01-01'), 'EEE, d MMM yyyy', 'en', 'GMT') QUIZDATE, QR.STUDENTID, CONCAT(S.FIRSTNAME,'',S.MIDDLENAME,' ',S.LASTNAME) STUDENTNAME, QR.QUIZQUESTIONID, QR.ANSWERVALID, CASE ANSWERVALID WHEN FALSE THEN 0 WHEN TRUE THEN 1 END AV "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZRUN QRN ON (QR.RUNID=QRN.IID) "
				+ "JOIN QUIZ Q ON (QRN.QUIZID=Q.IID) "
				+ "JOIN QUIZQUESTION QQ ON (QQ.QUIZID=Q.IID) "
				+ "LEFT JOIN STUDENT S ON (QR.STUDENTID=S.ID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' "
				+ ") "
				+ "GROUP BY STUDENTID " + "ORDER BY VALIDANSWERS";
	}

	public static String studentResult(UUID quizRunId) {
		return "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, FORMATDATETIME(DATEADD('SECOND', QRN.START/1000, DATE  '1970-01-01'), 'EEE, d MMM yyyy', 'en', 'GMT') QUIZDATE, QR.STUDENTID, CONCAT(S.FIRSTNAME,' ',S.MIDDLENAME,' ',S.LASTNAME) STUDENTNAME, QQ.ID QUIZQUESTIONID, "
				+ "CASE QR.ANSWERVALID WHEN FALSE THEN 'Incorrect' WHEN TRUE THEN 'Correct' END RESULT, "
				+ "CASE WHEN QQ.TYPE<3 THEN "
				+ "CONCAT( "
				+ "CASE QQ.BOOL1 WHEN TRUE THEN '(1)' ELSE '' END, "
				+ "CASE QQ.BOOL2 WHEN TRUE THEN '(2)' ELSE '' END, "
				+ "CASE QQ.BOOL3 WHEN TRUE THEN '(3)' ELSE '' END, "
				+ "CASE QQ.BOOL4 WHEN TRUE THEN '(4)' ELSE '' END, "
				+ "CASE QQ.BOOL5 WHEN TRUE THEN '(5)' ELSE '' END "
				+ ") "
				+ "WHEN QQ.TYPE=3 THEN "
				+ "CONCAT(QQ.BOOL1,',',QQ.BOOL2,',',QQ.BOOL3,',',QQ.BOOL4,',',QQ.BOOL5) ELSE '' END CORRECTANSWER, "
				+ "CASE WHEN QQ.TYPE<3 THEN "
				+ "CONCAT( "
				+ "CASE QR.BOOL1 WHEN TRUE THEN '(1)' ELSE '' END, "
				+ "CASE QR.BOOL2 WHEN TRUE THEN '(2)' ELSE '' END, "
				+ "CASE QR.BOOL3 WHEN TRUE THEN '(3)' ELSE '' END, "
				+ "CASE QR.BOOL4 WHEN TRUE THEN '(4)' ELSE '' END, "
				+ "CASE QR.BOOL5 WHEN TRUE THEN '(5)' ELSE '' END "
				+ ") "
				+ "WHEN QQ.TYPE=3 THEN QR.ANSWER ELSE '' END ANSWER, "
				+ "(CASE QR.ANSWERVALID WHEN FALSE THEN 0 WHEN TRUE THEN 1 END)*QQ.POINT ANSWERPOINT "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "LEFT JOIN STUDENT S ON (QR.STUDENTID=S.ID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' "
				+ "ORDER BY QR.QUIZQUESTIONID";
	}

	public static String pointChart(UUID quizRunId) {
		return "( SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE,COUNT(*) STUDENTCOUNT, SUM(POINTSUM), CONCAT('0-',QUIZPOINTS/5) POINTRANGE FROM( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, "
				+ "QR.STUDENTID, SUM(QQ.POINT) POINTSUM "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' AND QR.ANSWERVALID=TRUE "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, Q.POINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'),QR.STUDENTID) "
				+ "WHERE POINTSUM>0 AND POINTSUM<=QUIZPOINTS/5 "
				+ ") "
				+ "UNION ALL "
				+ "( "
				+ "SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE,COUNT(*) STUDENTCOUNT, SUM(POINTSUM), CONCAT((QUIZPOINTS/5)+1,'-',2*QUIZPOINTS/5) POINTRANGE FROM( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, QR.STUDENTID, SUM(QQ.POINT) POINTSUM "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' AND QR.ANSWERVALID=TRUE "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, Q.POINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'),QR.STUDENTID) WHERE POINTSUM>QUIZPOINTS/5 AND POINTSUM<=2*QUIZPOINTS/5 "
				+ ") "
				+ "UNION ALL "
				+ "( "
				+ "SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE,COUNT(*) STUDENTCOUNT, SUM(POINTSUM),CONCAT((2*QUIZPOINTS/5)+1,'-',3*QUIZPOINTS/5) POINTRANGE FROM( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, QR.STUDENTID, SUM(QQ.POINT) POINTSUM "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' AND QR.ANSWERVALID=TRUE "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, Q.POINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'),QR.STUDENTID) WHERE POINTSUM>2*QUIZPOINTS/5 AND POINTSUM<=3*QUIZPOINTS/5 "
				+ ") "
				+ "UNION ALL "
				+ "( "
				+ "SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE,COUNT(*) STUDENTCOUNT, SUM(POINTSUM),CONCAT((3*QUIZPOINTS/5)+1,'-',4*QUIZPOINTS/5) POINTRANGE FROM( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, QR.STUDENTID, SUM(QQ.POINT) POINTSUM "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' AND QR.ANSWERVALID=TRUE "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, Q.POINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'),QR.STUDENTID) WHERE POINTSUM>3*QUIZPOINTS/5 AND POINTSUM<=4*QUIZPOINTS/5 "
				+ ") "
				+ "UNION ALL "
				+ "( "
				+ "SELECT QUIZTITLE, QUIZCATEGORY, QUIZPOINTS, QUIZDATE,COUNT(*) STUDENTCOUNT, SUM(POINTSUM), CONCAT((4*QUIZPOINTS/5)+1,'-',QUIZPOINTS) POINTRANGE FROM( "
				+ "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, Q.POINTS QUIZPOINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, QR.STUDENTID, SUM(QQ.POINT) POINTSUM "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' AND QR.ANSWERVALID=TRUE "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, Q.POINTS, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'),QR.STUDENTID) WHERE POINTSUM>4*QUIZPOINTS/5 AND POINTSUM<=QUIZPOINTS "
				+ ")";
	}

	public static String radarChart() {
		return "SELECT S.ID STUDENTID, CONCAT(S.FIRSTNAME,' ',S.MIDDLENAME,' ',S.LASTNAME) STUDENTNAME, Q.ID QUIZID, Q.TITLE QUIZTITLE, SUM(QR.ANSWERVALID*QQ.POINT)*100/Q.POINTS POINTPERCENT "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "LEFT JOIN STUDENT S ON (QR.STUDENTID=S.ID) "
				+ "GROUP BY S.ID, S.FIRSTNAME, S.MIDDLENAME, S.LASTNAME, Q.IID ";
	}

	public static String answerRate(UUID quizRunId) {
		return "SELECT Q.TITLE QUIZTITLE, Q.CATEGORY QUIZCATEGORY, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT') QUIZDATE, QQ.ID, COUNT(QR.STUDENTID), SUM(QR.ANSWERVALID), SUM(QR.ANSWERVALID)*100/COUNT(QR.STUDENTID) CorrectAnswerPercent "
				+ "FROM QUIZRESPONSE QR "
				+ "JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.IID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.IID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "WHERE QRN.IID='"
				+ quizRunId
				+ "' "
				+ "GROUP BY Q.TITLE, Q.CATEGORY, FORMATDATETIME(DATEADD('SECOND',QRN.START/1000,DATE'1970-01-01'),'EEE, d MMM yyyy','en', 'GMT'), QQ.ID "
				+ "ORDER BY QQ.ID";
	}

	public static String surveyFeedback() {
		return "SELECT SUM(BOOL1)*100/COUNT(*) RESPONSEPERCENT, '(1)' QUESTIONNO "
				+ "FROM SURVEYRESPONSE SR JOIN SURVEYQUESTION SQ ON (SR.RESPONSEQUESTIONID=SQ.ID) "
				+ "JOIN SURVEY S ON (SQ.SURVEYID=S.ID) "
				+ "JOIN SURVEYRUN SRN ON (SQ.SURVEYID=SRN.SURVEYID) "
				+ "WHERE SRN.ID=1 AND SR.RESPONSEQUESTIONID=1 "
				+ "UNION ALL "
				+ "SELECT SUM(BOOL2)*100/COUNT(*) RESPONSEPERCENT, '(2)' QUESTIONNO "
				+ "FROM SURVEYRESPONSE SR JOIN SURVEYQUESTION SQ ON (SR.RESPONSEQUESTIONID=SQ.ID) "
				+ "JOIN SURVEY S ON (SQ.SURVEYID=S.ID) "
				+ "JOIN SURVEYRUN SRN ON (SQ.SURVEYID=SRN.SURVEYID) "
				+ "WHERE SRN.ID=1 AND SR.RESPONSEQUESTIONID=1 "
				+ "UNION ALL "
				+ "SELECT SUM(BOOL3)*100/COUNT(*) RESPONSEPERCENT, '(3)' QUESTIONNO "
				+ "FROM SURVEYRESPONSE SR JOIN SURVEYQUESTION SQ ON (SR.RESPONSEQUESTIONID=SQ.ID) "
				+ "JOIN SURVEY S ON (SQ.SURVEYID=S.ID) "
				+ "JOIN SURVEYRUN SRN ON (SQ.SURVEYID=SRN.SURVEYID) "
				+ "WHERE SRN.ID=1 AND SR.RESPONSEQUESTIONID=1"
				+ "UNION ALL "
				+ "SELECT SUM(BOOL4)*100/COUNT(*) RESPONSEPERCENT, '(4)' QUESTIONNO "
				+ "FROM SURVEYRESPONSE SR JOIN SURVEYQUESTION SQ ON (SR.RESPONSEQUESTIONID=SQ.ID) "
				+ "JOIN SURVEY S ON (SQ.SURVEYID=S.ID) "
				+ "JOIN SURVEYRUN SRN ON (SQ.SURVEYID=SRN.SURVEYID) "
				+ "WHERE SRN.ID=1 AND SR.RESPONSEQUESTIONID=1 "
				+ "UNION ALL "
				+ "SELECT SUM(BOOL5)*100/COUNT(*) RESPONSEPERCENT, '(5)' QUESTIONNO "
				+ "FROM SURVEYRESPONSE SR JOIN SURVEYQUESTION SQ ON (SR.RESPONSEQUESTIONID=SQ.ID) "
				+ "JOIN SURVEY S ON (SQ.SURVEYID=S.ID) "
				+ "JOIN SURVEYRUN SRN ON (SQ.SURVEYID=SRN.SURVEYID) "
				+ "WHERE SRN.ID=1 AND SR.RESPONSEQUESTIONID=1 "
				+ "UNION ALL "
				+ "SELECT 0 RESPONSEPERCENT, '(Not answered)' QUESTIONNO ";
	}
}
