package com.jajeem.util;

public class Query {
	
	public static String SummaryOfStudents(int quizId) {
		return "SELECT QUIZTITLE,QUIZCATEGORY,QUIZPOINTS,QUIZDATE,STUDENTID,STUDENTNAME,COUNT(ANSWERVALID) QUESTIONCOUNT,SUM(AV) VALIDANSWERS, SUM(AV)*100/COUNT(ANSWERVALID) PERCENTS,SUM(AV)*QUIZPOINTS/COUNT(ANSWERVALID)POINTS FROM ( "
				+ "SELECT Q.TITLE QUIZTITLE,Q.CATEGORY QUIZCATEGORY,Q.POINTS QUIZPOINTS,FORMATDATETIME(DATEADD('SECOND', QRN.START/1000, DATE '1970-01-01'),    'EEE, d MMM yyyy', 'en', 'GMT') QUIZDATE,QR.STUDENTID,CONCAT(S.FIRSTNAME,' ',S.MIDDLENAME,' ',S.LASTNAME) STUDENTNAME,QR.QUIZQUESTIONID,QR.ANSWERVALID, "
				+ "CASE ANSWERVALID WHEN FALSE THEN 0 WHEN TRUE THEN 1 END AV "
				+ "FROM QUIZREPONSE QR JOIN QUIZQUESTION QQ ON (QR.QUIZQUESTIONID=QQ.ID) "
				+ "JOIN QUIZ Q ON (QQ.QUIZID=Q.ID) "
				+ "JOIN QUIZRUN QRN ON (QQ.QUIZID=QRN.QUIZID) "
				+ "JOIN STUDENT S ON (QR.STUDENTID=S.ID) "
				+ "WHERE QRN.ID="+ quizId +") "
				+ "GROUP BY STUDENTID "
				+ "ORDER BY VALIDANSWERS ";
	}
	
}
